### ISSUE TITLE
Correct answer not in choices selection

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#1]
![correct_answer_is_not_offered_as_answer_option](https://cloud.githubusercontent.com/assets/1112023/19855832/8a37ccbc-9f6e-11e6-82d8-0df03d1fc781.png)

The correct answer is 'female' which is not offered as an option to choose from.

The problem is in module 'repeat.js' which deals with this.

**Comment by hhzl** [comment]
Suggestion for a solution:

The function `showWord` in the module `repeat.js` should rely on two other functions `w = chooseWord()` and `answerOptions = selectAnswerOptionsFor(w) `

**Comment by e1r0nd** [comment]
Fixed
