### ISSUE TITLE
Add Unit test

### ISSUE THREAD

**Issue by e1r0nd** [e1r0nd/LearnWords#21]
Add unit testts

**Comment by hhzl** [comment]
Jasmine?

**Comment by e1r0nd** [comment]
Jasmine is fine.

**Comment by hhzl** [comment]
So far
https://github.com/hhzl/LearnWords/tree/Jasmine

**Comment by e1r0nd** [comment]
I prefer to take this project as "pure" as possible, without tools/dependencies. Without Grunt/Gulp/Bower... Just npm.

**Comment by hhzl** [comment]
I am fine with this.

But I prefer the browser version of Jasmine, not the npm
https://www.npmjs.com/package/jasmine

"This module allows you to run Jasmine specs for your Node.js code. The output will be displayed in your terminal by default."

Or do you think of a different npm / Jasmine setup.

**Comment by e1r0nd** [comment]
I use unit tests (with Jasmine) as part of CI, therefore prefer a terminal version.

**Comment by hhzl** [comment]
Ok, I agree. Let's go for the terminal version.

This package https://www.npmjs.com/package/jasmine ?

**Comment by hhzl** [comment]
For a Jasmine test setup for LWdb.js see https://github.com/hhzl/LearnWords2/releases/tag/v0.1-beta2.

@e1r0nd please close this issue.

**Comment by e1r0nd** [comment]
Started. Mocha.
