### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by e1r0nd** [e1r0nd/LearnWords#22]
Remove jQuery

**Comment by hhzl** [comment]
What is the impact of this request? What does it affect?

Is it mainly

       document.getElementsById(...)

? 
I did not look much at the GUI code yet.

**Comment by e1r0nd** [comment]
There are more: on, click, each, data, text, val, ready, etc.
You can look for '$(' in *.js

**Comment by hhzl** [comment]
Just curious: what is the main reason for removing jQuery?

**Comment by e1r0nd** [comment]
"You wanted a banana but what you got was a gorilla holding the banana and the entire jungle." (c) Joe Armstrong
~70-80% of jQuery functions is not used in this app.

**Comment by hhzl** [comment]
I suggest that this issue is split into _pomodoro duration _ (25min) sized sub-issues.

**Comment by hhzl** [comment]
And what about going for zepto [(github](https://github.com/madrobby/zepto), [web site](http://zeptojs.com/)).

See also
http://lea.verou.me/2015/04/jquery-considered-harmful/

**Comment by e1r0nd** [comment]
The original idea is to eliminate all external dependencies (jQuery and Bootstrap) and use plain JS/CSS. Otherwise jQuery/Bottstrap/otherlibrary could be used and should be used on 60-80%

**Comment by e1r0nd** [comment]
maybe next time...
