### ISSUE TITLE
Move code base to ES6

### ISSUE THREAD

**Issue by e1r0nd** [e1r0nd/LearnWords#25]
Move code base to ES6

package.json
```
  "dependencies": {
    "google-closure-compiler": "^20160315.2.0"
  }
  "scripts": {
    "compile": "java -jar node_modules/google-closure-compiler/compiler.jar -O ADVANCED --language_in=ES6_STRICT --new_type_inf --js_output_file='dist/bundle.js' --js='src/**.js' -W VERBOSE"
...
  }
```

`npm run compile`

**Comment by hhzl** [comment]
Maybe first ECMAScript 5? 
So far no `arr.filter(...)` [1] used.

Where do you see the need for ES6?

[1]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by e1r0nd** [comment]
Everywhere :)
Pseudo-classes to ES6 Classes; $(selector) to getElement*; $.forEach to array.forEach; etc.

**Comment by e1r0nd** [comment]
done. partially :)
