### ISSUE TITLE
Learn-mode buttons

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#3]
If a word is not known in the repeat mode it goes back to the learn-mode-box (the first box in the Leitner system [1]).

![learn_mode](https://cloud.githubusercontent.com/assets/1112023/19855927/01fc8904-9f6f-11e6-8bdd-a68b8577c1e5.png)

[1] https://en.wikipedia.org/wiki/Leitner_system

Note:  In the LearnWords app the boxes are labeled 
- step 0  (Learn mode)
- step 1 (Repeat mode)
- step 2 (Repeat mode)
- step 3 (Repeat mode)

Question: Is this correct? How are the transistions from one mode to the othr mode?

**Comment by e1r0nd** [comment]
Used an alternative method where incorrect answers are only moved back by one box. [1]
Answered words are moved forward (step N+1), not answered are moved back (step N-1).
![image](https://cloud.githubusercontent.com/assets/2270509/19867034/de8d2a76-9fa2-11e6-9ac7-4d9fbf6c6e15.png)

[1] https://en.wikipedia.org/wiki/Leitner_system

**Comment by hhzl** [comment]
Thank you for the clarification.

Another question:
Labelling of the boxes in this LearnWord app starts with 0, that is 'step 0'. This is what is displayed in the _learn_ mode.

What do the buttons
- remember
- repeat
- known 

do? Which transitions are they supposed to trigger?

**Comment by e1r0nd** [comment]
* remember - move to the next box (Step 1)
* repeat - leave it this box (for Step 0)
* known - give it away (know this word for sure)

**Comment by e1r0nd** [comment]
Fixed
