### ISSUE TITLE
Combine all actions files into actions.js

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#33]
For easier re-factoring of all files in the actions folder should be combined (global search/replace).

**Comment by e1r0nd** [comment]
Could it be more convenient using one huge file instead separate modules/components?

**Comment by hhzl** [comment]
A hug file all.js would be convenient for working on the app in the next weeks.

Later we might want to split it again because the file structure
showed quite neatly how the app is structured. This was a big help for
me to see what is going on. But at the moment I do not need it
anymore.

And we should pack all objects as sub-objects under one global

        LW

object.
