### ISSUE TITLE
Add setup screen for loading words initially.

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#35]
The first time the app runs there are no words stored in the web browser storage area.

Thus the words defined in memorystore.js are loaded.

Instead of that the user should see a setup screen where he or she can use a word list file to be loaded. The files could come from various places (just web links).

**Comment by hhzl** [comment]
See also #46

**Comment by e1r0nd** [comment]
Not actual. Actions have been separated to components.
