### ISSUE TITLE
Replace Repeat.wordsRepeat.first with LW.wordsToRepeat

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#40]
See
https://github.com/e1r0nd/LearnWords/blob/master/js/actions/repeat.js

Do the following repleacements

     Repeat.wordsRepeat.first

with

     Repeat.box[1]

then

     Repeat.wordsRepeat.second

with

     Repeat.box[2]

And finally

     Repeat.wordsRepeat.third

with

     Repeat.box[3]

Adapt the code in https://github.com/e1r0nd/LearnWords/blob/master/js/actions/repeat.js to be fine with this change.

The code will be then be shorter and more readable.

**Comment by hhzl** [comment]
Or better

       LW.rpt.box[1]

       LW.rpt.box[2]

       LW.rpt.box[3]

Move the Repeat object under the global LW object as a sub-object.

**Comment by hhzl** [comment]
Replacements

Replace in file action.js

      Repeat.

 (repeat plus full stop)

with 

     LW.rpt.


And then

       LW.rpt.first

with 

       LW.rpt.box[1]

**Comment by hhzl** [comment]
Can

     LW.rpt.wordsRepeat.box

be shortened to

    LW.rpt.box

As we are in the repeat mode. wordsRepeat seems to be redundant.

**Comment by hhzl** [comment]
New insight:

It is about replacing the 

      Repeat.wordsRepeat 

**object** with an **array**.

And _wordsRepeat_ actually means _wordsToRepeat_ . 

Probably we should have something like

      LW.rpt.box[..]

replacing 

      Repeat.wordsRepeat

What do you think, Anatol?

**Comment by e1r0nd** [comment]
I want to keen code readable, 'self-documented'. Something like 'rptbox' will broke this rule.

**Comment by hhzl** [comment]
Which name do you propose then for 

      Repeat.wordsToRepeat

?

**Comment by e1r0nd** [comment]
"Repeat.wordsToRepeat" sounds good for me.

**Comment by hhzl** [comment]
I am fine with `wordsToRepeat`.

But not with `Repeat.wordsToRepeat`.

* It is redundant
* There are many expressions where this occurs and this makes the code lines unnecessary long.

I propose this solution:

We make `wordsToRepeat` a sub-object of the global `LW` object

       LW.wordsToRepeat

* It is short.
* It is a contribution to unclutter the global name space. We have started packing objects under a global LW object (cf jQuery $)

**Comment by e1r0nd** [comment]
I agree with converting "LearnWords" to "LW" or "Repeat" to "R", but not with "wordsToRepeat" to "wtr".
Global objects could have shortcuts, properties should be readable.

**Comment by hhzl** [comment]
This will be compatible with https://github.com/hhzl/LearnWords2/issues/63

**Comment by e1r0nd** [comment]
Not actual. Actions have been separated to components.
