### ISSUE TITLE
Question: learnWordsTopNum vs.  learnWordsTopSNum?

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#41]
Issue https://github.com/e1r0nd/LearnWords/issues/38 has

    $(learnWordsNum).text(wordsLearnLength || '0');
    $(learnWordsTopNum).text(wordsLearnLength);
    $(learnWordsTopSNum).text(wordsLearnLength);

What do these fields 
- learnWordsNum
- learnWordsTopNum
- learnWordsTopSNum

mean?

**Comment by e1r0nd** [comment]
Fields have been removed.
