### ISSUE TITLE
fix: destroyDB() and isEmpty()

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#47]
Add resetting the index to the destroy function

current

	destroy: function(){

                        var aKeyPrefix = LW.db.name;  

                        LW.db.removeObjects(aKeyPrefix);

		},

new

	destroy: function(){

                        var aKeyPrefix = LW.db.name;  

                        LW.db.removeObjects(aKeyPrefix);
                        LW.db.index = null;
		},

And the the check for `isEmpty()`

Current

       isEmpty: function(key){
	   		if (LW.db.isOK) {
				if (LW.db.index.length == 0) {return true} else {return false};
			}
		},

New

       isEmpty: function(key){
	   		if (LW.db.isOK) {
				if (LW.db.index == null || LW.db.index.length == 0) {return true} else {return false};
			}
		},

**Comment by hhzl** [comment]
Implemented in [this branch](https://github.com/hhzl/LearnWords/tree/LearnWords2016).

**Comment by e1r0nd** [comment]
Not actual. Actions have been separated to components.
