### ISSUE TITLE
Move of words from 'Learn' mode to 'Repeat' mode seems to be broken

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#48]
Some people testing the app have reported that the 'Repeat' mode seems not to work for words which have been moved from the 'Learn' mode to the 'Repeat' mode.

**Reason**
This depends on the fact that a word which is in the learn mode gets a new date put on it which is **one day later**.  But there is no visual clue indicating this. The Repeat mode just seems to be empty.

It has to do with this code
https://github.com/e1r0nd/LearnWords/blob/master/js/actions/actions.js#L152
````
          actionWord: function(step, reindex) {
                if (step) {
                    var word = {
                        index: Learn.wordsLearn[Learn.currentIndex].index,
                        word: Learn.wordsLearn[Learn.currentIndex].word,
                        translate: Learn.wordsLearn[Learn.currentIndex].translate,
                        step: step,
                        date: (step == 1) ? (Utils.getToday() + Utils.delay * Settings.params.first) : 0
                    };

                    LW.db.storeItem(LW.db.name+'-' + Learn.wordsLearn[Learn.currentIndex].index, word); //save word

                    if (reindex) {
                        Learn.wordsLearn.splice(Learn.currentIndex, 1); //remove from index
                        Learn.recountIndexLearn();
                    } else {
                        Learn.currentIndex++;
                    }
                } else {
                    Learn.currentIndex++;
                }

                if (Learn.currentIndex >= Learn.wordsLearn.length) {
                    Learn.currentIndex = 0;
                }
                Learn.showWord();
            },
````

**Solution**
It would be better if the date which is applied to the word when it moves from `learn` to `repeat` mode is  `today minus a small amount` so that the word shows up in the Repeat tab.

**Comment by hhzl** [comment]
Note: the title says 

_Move of words from 'Learn' mode to 'Repeat' mode **seems** to be broken_

Actually I think it works fine but as there is **not enough feedback** the user can get the impression that it is broken.

**Comment by e1r0nd** [comment]
Could be this case covered by #45 ?

**Comment by hhzl** [comment]
Yes that would help to **show** the user that the app is working because there is immediate feedback.

However I would leave it up to the user to decide when he or she wants to start repeating.

This means when a word is moved from step 0 to step 1 the date should be just today and not today plus 1 day. Thus the words will show up in the repeat mode.

**Comment by e1r0nd** [comment]
Would #53 cover this case?
In "empty" repeat mode show "Nothing right now" and a button "Repeat now".

**Comment by e1r0nd** [comment]
Not actual. This action should be redo.
