### ISSUE TITLE
About replacing memorystore.js - which date?

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#5]
I'd like to replace memorystore.js with my own version having a different set of words.

I wonder what the conditions for the data are. 

It seems that the date value is not allowed to be undefined. 
A value of 0 is better in the sense that the words show up in the **LearnMode**. However they are not promoted properly in the **Repeat** mode.

https://github.com/e1r0nd/LearnWords/blob/master/js/utils/memorystore.js

All words should show up in the **Learn** mode first and then when the user wants it appear in the **Repeat** mode and go through steps 1 to 3.

Other remarks / comments about the nature of the input data?

**Comment by hhzl** [comment]
A partial success was this data; date value set to 0.

/**************************************************
* Learn Words // memorystore.js
* The in-memory Store. Encapsulates logic to access data.
* All fields are required.
*
* Hannes Hirzel, 28 Oct 2016
*
* Placed in public domain.
**************************************************/

localStorageAPI.storeItem('learnWords-settings', settings);
localStorageAPI.storeItem('learnWords-language', 'en_GB');


word = {"index":"index1","word":"Apfel","translate":"apple","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index1', word);

word = {"index":"index10","word":"Guava","translate":"guava","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index10', word);

word = {"index":"index11","word":"Banane","translate":"banana","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index11', word);

word = {"index":"index12","word":"Melone","translate":"melon","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index12', word);


var words = ["index1","index10","index11","index12"];


localStorageAPI.storeItem('learnWords-words', words.join());



console.log('memorystore.js');

**Comment by hhzl** [comment]
And the follwoing data has the date value initialized with

d = new Date("2016-11-01");
JSON.stringify(d)

/*
"2016-11-01T00:00:00.000Z"
*/

Thus by using this file all records have an earlier date than today.

**Comment by hhzl** [comment]
/**************************************************
* Learn Words // memorystore.js
* The in-memory Store. Encapsulates logic to access data.
* All fields are required.
*
* Hannes Hirzel, 28 Oct 2016
*
* Placed in public domain.
**************************************************/

localStorageAPI.storeItem('learnWords-settings', settings);
localStorageAPI.storeItem('learnWords-language', 'en_GB');


word = {"index":"index1","word":"Apfel","translate":"apple","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index1', word);

word = {"index":"index10","word":"Guava","translate":"guava","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index10', word);

word = {"index":"index11","word":"Banane","translate":"banana","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index11', word);

word = {"index":"index12","word":"Melone","translate":"melon","date":0,"step":1};
localStorageAPI.storeItem('learnWords-index12', word);


var words = ["index1","index10","index11","index12"];


localStorageAPI.storeItem('learnWords-words', words.join());



console.log('memorystore.js');

**Comment by e1r0nd** [comment]
This file is used only for demo date for the fresh installation. Once User decided to start he should delete default words (installed by memorystore.js file) and enter his own via interface.
The "normal" way for creating new words is the User Interface.
