### ISSUE TITLE
Refine and document LWdb API

### ISSUE THREAD

**Issue by hhzl** [e1r0nd/LearnWords#58]
Document and update the LWdb API  for the currently two active branches.

https://github.com/e1r0nd/LearnWords/wiki

Get a unified API which later may be used for adapting to other databases.

**Comment by hhzl** [comment]
For the two active branches 

- db related
- settings related 

methods are the same.

For the words related methods there are differences:

LearnWords2016
````
get: function(key){
put: function(key, value){
remove: function(key){
````


Master
````
readItem: function(key){
removeItem: function(key){
storeItem: function(key, value){
````

## Suggestion

Use
````
getWord: function(key){
removeWord: function(key){
putWord: function(key, value){
````

**Comment by hhzl** [comment]
The index of all keys of the all words is also part of the API. It is a property, not a method.

**Comment by hhzl** [comment]
See also https://github.com/hhzl/LearnWords2. It contains a ``LWdb.js`` component which should be mostly compatible (to be verified).

**Comment by e1r0nd** [comment]
File has been moved to actions and completely changed.
